### PR TITLE
Generate Trino group mapping

### PR DESCRIPTION
**Pull request by mbacovsky**
DataHub team is working on getting LDAP groups support to Trino.
As a preparation step I unified the CCX related Rover groups
and group mapping in Trino config.

With this PR I'm proposing to use the roevr groups to drive access to
Trino as well as to Superset. To make this easier before Trino gets
LDAP support I prepared a Makefile that updates the group mapping
from the Rover group.

```
$ make help
update-ccx-groups              Update ccx trino access groups from LDAP
$ make update-ccx-groups
```

The procedure to onboard new user to Trino should be to update the rover
group, call the `make update-ccx-groups` and submit a PR.

The important thing to watch is not to allow manual addition to the group
mapping without addition to the Rover group.

### CODE REVIEW

**Comment by mbacovsky** [comment]
@accorvin I like the idea to include also the other groups. How that would work?
Can we use the map from Superset config?
Should we generate the same trino groups as now containing all the collected users?
Or create new groups matching the ldapgroups and then generate the trino-acl-rules accordingly?
Something else?

**Comment by accorvin** [comment]
@mbacovsky I think the thing to do is to update this makefile to include lines for all of the groups that we care about. I'm going to go ahead and merge this in as I need to add a new entry to the groups list and I don't want to introduce a merge conflict. I'll then submit another PR adding the additional groups.

**Comment by accorvin** [comment]
@mbacovsky just for visibility, I've submitted https://github.com/AICoE/internal-data-hub/pull/411 which updates this makefile to functionify it a bit and start pulling in more groups to sync. I'll add the additional groups for ccx permissions in superset later today (I'm splitting it into multiple PRs to make for easier reviews)

**Pull request merged**
