### PR TITLE
Update obslytics metadata print statement to conform to python version

### PR DESCRIPTION
**Pull request by gmfrasca**

### CODE REVIEW

**Comment by accorvin** [comment]
Does obslytics run on python 2?

/lgtm

**Review by DharmitD — COMMENTED** [review]
/approve

**Review by DharmitD — APPROVED** [review]
/approve

**Comment by gmfrasca** [comment]
> Does obslytics run on python 2?
> 
> /lgtm

no, most of it is in go, but the pyscripts image we do use is on 3.7 or 3.8.  its *just* the final 2 steps that interact with trino that we appended to the end (and are technically unrelated to obslytics itself, just added here for sync reasons)  which use the quay.io/opendatahub/trino:365 image, which apparently uses Python 2.7

**Pull request merged**
