### PR TITLE
Fix cpu resource request and termination message items in app spec

### PR DESCRIPTION
**Pull request by accorvin**

### CODE REVIEW

**Review by HumairAK — APPROVED** [review]

**Comment by goern** [comment]
@harshad16 do we need sefkhet-abwy in here to add the approved label automatically, so that tide merges automatically?

**Comment by harshad16** [comment]
> @harshad16 do we need sefkhet-abwy in here to add the approved label automatically, so that tide merges automatically?

yes , christoph we need sefkhet-abwy, i was under the impression sfkhet-abwy is enable on all repos in aicoe.

**Comment by goern** [comment]
hmmm, it is ?:/

**Comment by goern** [comment]
hmm, the repos are missing labels.... I'll create them

**Pull request merged**
