### PR TITLE
Grant all Telemetry groups the CCX role in Superset

### PR DESCRIPTION
**Pull request by accorvin**
We want all people with access to Telemetry data to have the CCX role in
Superset. Previously, we only granted this access to one of the
Telemetry groups. This change adds the role to the other two groups.

### CODE REVIEW

**Review by lucferbux — APPROVED** [review]
/lgtm

**Review by gmfrasca — COMMENTED** [review]
/lgtm

**Review by DharmitD — APPROVED** [review]
/approve

**Pull request merged**
