### PR TITLE
Obslytics metrics metadata

### PR DESCRIPTION
**Pull request by gmfrasca**

### CODE REVIEW

**Review by lucferbux — COMMENTED** [review]
/lgtm

**Comment by lucferbux** [comment]
@gmfrasca seems to be right, all the overlays seem to be applying as expected, I still need to run the workflow in a dev cluster to check it.
The only suggestion: squash the last commit of the PR.

**Comment by gmfrasca** [comment]
I'd disagree with the squash, they are 2 distinct updates/actions and should be kept separated as such (one to remove 'old' non-backfill ETL pipeline, and the other to implement metadata-enriched metric list)

**Comment by anishasthana** [comment]
Fwiw I think I agree with Giulio as well.

**Review by anishasthana — APPROVED** [review]

**Pull request merged**
