### PR TITLE
Adjust backfill_to metadata

### PR DESCRIPTION
**Pull request by gmfrasca**

### CODE REVIEW

**Comment by gmfrasca** [comment]
since bots are down, manually ran pre-commit, which passes:
```
(internal-data-hub) [gfrasca@localhost internal-data-hub]$ pre-commit run --all-files
Tabs remover.............................................................Passed
Trim Trailing Whitespace.................................................Passed
Check for merge conflicts................................................Passed
Fix End of Files.........................................................Passed
Check for added large files..............................................Passed
Check for case conflicts.................................................Passed
Check JSON...........................................(no files to check)Skipped
Check for broken symlinks............................(no files to check)Skipped
Detect Private Key.......................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
yamllint.................................................................Passed
(internal-data-hub) [gfrasca@localhost internal-data-hub]$ 
```

**Review by anishasthana — COMMENTED** [review]
/lgtm

**Review by anishasthana — APPROVED** [review]

**Review by anishasthana — APPROVED** [review]

**Pull request merged**
